# Generated by Django 4.2.5 on 2024-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodie',
            name='manga',
            field=models.CharField(default='MHA', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='manga',
            field=models.CharField(default='MHA', max_length=50),
        ),
    ]
