# Generated by Django 4.2.5 on 2024-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_remove_goodie_manga_remove_product_manga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='goodie',
            name='category',
            field=models.CharField(choices=[('MHA', 'MHA'), ('Naruto', 'Naruto'), ('OnePiece', 'OnePiece')], default='MHA', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MHA', 'MHA'), ('Naruto', 'Naruto'), ('OnePiece', 'OnePiece')], default='MHA', max_length=128),
            preserve_default=False,
        ),
    ]
